(:init
    (ontable purple_block)
    (ontable orange_block)
    (ontable red_block)
    (ontable yellow_block)
    (ontable green_block)
    (clear green_block)
    (on green_block orange_block)
    (on orange_block blue_block)
    (handempty robot)
)