(:init
    (ontable purple_block)
    (ontable orange_block)
    (ontable red_block)
    (clear yellow_block)
    (clear green_block)
    (clear red_block)
    (on yellow_block purple_block)
    (on green_block orange_block)
    (handempty robot)
)