(:init
    (ontable orange_block)
    (ontable purple_block)
    (ontable red_block)
    (ontable yellow_block)
    (ontable green_block)
    (clear orange_block)
    (clear purple_block)
    (clear red_block)
    (clear yellow_block)
    (clear green_block)
    (handempty robot)
)