(:init
    (ontable purple_block)
    (ontable orange_block)
    (clear red_block)
    (clear orange_block)
    (clear green_block)
    (on red_block yellow_block)
    (on yellow_block purple_block)
    (on green_block orange_block)
    (handempty robot)
)